### ISSUE TITLE
configuration.h error: 'signals' does not name a type

### ISSUE THREAD

**Issue by Lionhair** [embeddedartists/labtool#10]
When I try to compile the code on my Fedora 22, I get the following error

/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++-64 -o configuration.o common/configuration.cpp
In file included from common/configuration.cpp:16:0:
common/configuration.h:69:1: error: ‘signals’ does not name a type
 signals:
 ^
common/configuration.h: In static member function ‘static Configuration& Configuration::instance()’:
common/configuration.h:29:30: error: no matching function for call to ‘Configuration::Configuration()’
         static Configuration singleton;
                              ^
common/configuration.h:77:5: note: candidate: Configuration::Configuration(const Configuration&)
     Configuration(const Configuration&);
     ^
common/configuration.h:77:5: note:   candidate expects 1 argument, 0 provided
common/configuration.cpp: At global scope:
common/configuration.cpp:63:1: error: prototype for ‘Configuration::Configuration()’ does not match any in class ‘Configuration’
 Configuration::Configuration()
 ^
In file included from common/configuration.cpp:16:0:
common/configuration.h:77:5: error: candidate is: Configuration::Configuration(const Configuration&)
     Configuration(const Configuration&);
     ^
Makefile:2127: recipe for target 'configuration.o' failed
make: *** [configuration.o] Error 1

**Comment by embeddedartists** [comment]
We haven't tried to compile LabTool in Fedora, but we have instructions for how to do it in Windows and on Raspberry Pi (which runs Linux).

https://github.com/embeddedartists/labtool/blob/master/app/COMPILE.raspi.md

**Comment by embeddedartists** [comment]
The problem could be that the Configuration object isn't defined as a QObject. Signals and slots are actually not used by this class so you can try to remove 'signals:' and 'public slots:' from the header file and see if it compiles

**Comment by Lionhair** [comment]
I commented out "Signals" and "slots" and this made the software compile.

I new feel confident enough to try and order the Labtool - thank you for
the help.


Best regards
Esben
