### ISSUE TITLE
Possibility to make the signals larger ?

### ISSUE THREAD

**Issue by mtk11** [embeddedartists/labtool#19]
It seems LabTool shows the signals with predefined height. This is kind of inconvenient when used for measuring and observing analog signals. Any way to make the presented signals height adjustable or fill the whole window ?

![LabTool](https://user-images.githubusercontent.com/73300694/131827969-2a8e3b50-df34-4e36-ab4d-b78686e9a8a7.jpg)

**Comment by embeddedartists** [comment]
LabTool currently doesn't support making the signal view large.
