### ISSUE TITLE
 labtool/fw/gcc_arm.ld code problem

### ISSUE THREAD

**Issue by HAPI-Tech-Solution** [embeddedartists/labtool#9]
Dear all,
I contact to LPC. They say is following.
https://www.lpcware.com/content/forum/lpc4370-memory-configuration-err

”Because it is RAM at that location. IT IS NOT FLASH, SO DO NOT DEFINE IT AS FLASH.”

I try to LPC recommend all RAM area memory config, RevC chip is working.
But, First RAM area Flash ld script is not working.
If you can change and testing ld script, please confirm.

Regards,

**Comment by embeddedartists** [comment]
Hi,

This is not a problem. FLASH is just a name it could be called anything. The comment clearly says "76k of RAM used as ROM".

I have renamed the symbol to ROM instead (see commit 99fdb8eaf4847f419dc8771ee2b0f96b8a2034f5) to possibly make it clearer, but it is only an aesthetic thing as it makes absolutely no difference in the produced binary.

Best Regards,
Anders @ Embedded Artists

**Comment by HAPI-Tech-Solution** [comment]
hank you for your reply.
Yes, I believe your answer. But, LPC is say very confuse.
